# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peek.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeek.proto\x12\x04peek\"1\n\x0buserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\x0cuserResponse\x12\x0e\n\x06userID\x18\x01 \x01(\x05\"\x9b\x01\n\x0bpeekRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x05\x12$\n\x05\x61ppID\x18\x02 \x01(\x0e\x32\x15.peek.peekRequest.app\"V\n\x03\x61pp\x12\t\n\x05GMAIL\x10\x00\x12\r\n\tINSTAGRAM\x10\x01\x12\x0b\n\x07\x44ISCORD\x10\x02\x12\x0c\n\x08WHATSAPP\x10\x03\x12\r\n\tMESSENGER\x10\x04\x12\x0b\n\x07TWITTER\x10\x05\"+\n\x0cpeekResponse\x12\x1b\n\x06topics\x18\x01 \x03(\x0b\x32\x0b.peek.topic\"e\n\x05topic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65moji\x18\x02 \x01(\t\x12\x11\n\thighlight\x18\x03 \x01(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x1b\n\x06notifs\x18\x05 \x03(\x0b\x32\x0b.peek.notif\"#\n\x05notif\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t2\xe0\x01\n\x0bpeekService\x12\x30\n\x07\x61\x64\x64User\x12\x11.peek.userRequest\x1a\x12.peek.userResponse\x12\x32\n\tloginUser\x12\x11.peek.userRequest\x1a\x12.peek.userResponse\x12\x36\n\rgetCachedData\x12\x11.peek.peekRequest\x1a\x12.peek.peekResponse\x12\x33\n\ngetNewData\x12\x11.peek.peekRequest\x1a\x12.peek.peekResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peek_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=20
  _USERREQUEST._serialized_end=69
  _USERRESPONSE._serialized_start=71
  _USERRESPONSE._serialized_end=101
  _PEEKREQUEST._serialized_start=104
  _PEEKREQUEST._serialized_end=259
  _PEEKREQUEST_APP._serialized_start=173
  _PEEKREQUEST_APP._serialized_end=259
  _PEEKRESPONSE._serialized_start=261
  _PEEKRESPONSE._serialized_end=304
  _TOPIC._serialized_start=306
  _TOPIC._serialized_end=407
  _NOTIF._serialized_start=409
  _NOTIF._serialized_end=444
  _PEEKSERVICE._serialized_start=447
  _PEEKSERVICE._serialized_end=671
# @@protoc_insertion_point(module_scope)
